2016-12-07 23:08:26,394 |OFBiz-config-2       |DatabaseUtil                  |E| Unable to establish a connection with the database for helperName [localpostolap]... Error was: java.sql.SQLException: Unable to acquire a new connection from the pool
2016-12-07 23:08:26,394 |OFBiz-config-1       |DatabaseUtil                  |E| Unable to establish a connection with the database for helperName [localpostnew]... Error was: java.sql.SQLException: Unable to acquire a new connection from the pool
2016-12-07 23:08:26,395 |OFBiz-config-2       |DatabaseUtil                  |E| Unable to establish a connection with the database, no additional information available.
2016-12-07 23:08:26,395 |OFBiz-config-1       |DatabaseUtil                  |E| Unable to establish a connection with the database, no additional information available.
2016-12-07 23:08:26,395 |OFBiz-config-1       |DatabaseUtil                  |E| Could not get table name information from the database, aborting.
2016-12-07 23:08:26,396 |OFBiz-config-2       |DatabaseUtil                  |E| Could not get table name information from the database, aborting.
2016-12-07 23:08:26,397 |OFBiz-config-0       |DatabaseUtil                  |E| Unable to establish a connection with the database for helperName [localposttenant]... Error was: java.sql.SQLException: Unable to acquire a new connection from the pool
2016-12-07 23:08:26,397 |OFBiz-config-0       |DatabaseUtil                  |E| Unable to establish a connection with the database, no additional information available.
2016-12-07 23:08:26,397 |OFBiz-config-0       |DatabaseUtil                  |E| Could not get table name information from the database, aborting.
2016-12-07 23:08:30,125 |main                 |GenericDelegator              |E| Failure in removeByCondition operation for entity [ServiceSemaphore]: org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)). Rolling back transaction.
org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool))
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1202) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1110) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1091) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1084) [ofbiz-entity-test.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:111) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:142) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getInstance(ServiceDispatcher.java:176) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getLocalDispatcher(ServiceDispatcher.java:153) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory.createLocalDispatcher(GenericDispatcherFactory.java:40) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceContainer.getLocalDispatcher(ServiceContainer.java:90) [ofbiz-service.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getLocalDispatcher(EntityServiceFactory.java:34) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getDispatchContext(EntityServiceFactory.java:39) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.eca.DelegatorEcaHandler.setDelegator(DelegatorEcaHandler.java:53) [ofbiz-entityext.jar:?]
	at org.ofbiz.entity.GenericDelegator.initEntityEcaHandler(GenericDelegator.java:333) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.DelegatorFactory.getDelegator(DelegatorFactory.java:42) [ofbiz-entity-test.jar:?]
	at org.ofbiz.catalina.container.CatalinaContainer.init(CatalinaContainer.java:190) [ofbiz-catalina.jar:?]
	at org.ofbiz.base.container.ContainerLoader.loadContainer(ContainerLoader.java:185) [ofbiz-base.jar:?]
	at org.ofbiz.base.container.ContainerLoader.load(ContainerLoader.java:121) [ofbiz-base.jar:?]
	at org.ofbiz.base.start.Start.initStartLoaders(Start.java:273) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.init(Start.java:241) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.main(Start.java:127) [ofbiz.jar:?]
Caused by: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
2016-12-07 23:08:30,555 |main                 |ServiceDispatcher             |E| null
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)) (Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)))
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1156) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1110) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1091) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1084) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:111) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:142) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getInstance(ServiceDispatcher.java:176) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getLocalDispatcher(ServiceDispatcher.java:153) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory.createLocalDispatcher(GenericDispatcherFactory.java:40) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceContainer.getLocalDispatcher(ServiceContainer.java:90) [ofbiz-service.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getLocalDispatcher(EntityServiceFactory.java:34) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getDispatchContext(EntityServiceFactory.java:39) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.eca.DelegatorEcaHandler.setDelegator(DelegatorEcaHandler.java:53) [ofbiz-entityext.jar:?]
	at org.ofbiz.entity.GenericDelegator.initEntityEcaHandler(GenericDelegator.java:333) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.DelegatorFactory.getDelegator(DelegatorFactory.java:42) [ofbiz-entity-test.jar:?]
	at org.ofbiz.catalina.container.CatalinaContainer.init(CatalinaContainer.java:190) [ofbiz-catalina.jar:?]
	at org.ofbiz.base.container.ContainerLoader.loadContainer(ContainerLoader.java:185) [ofbiz-base.jar:?]
	at org.ofbiz.base.container.ContainerLoader.load(ContainerLoader.java:121) [ofbiz-base.jar:?]
	at org.ofbiz.base.start.Start.initStartLoaders(Start.java:273) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.init(Start.java:241) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.main(Start.java:127) [ofbiz.jar:?]
Caused by: org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool))
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1202) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
2016-12-07 23:08:48,494 |catalina-startup-1   |UtilXml                       |E| XmlFileLoader: File jndi:/0.0.0.0/imscenter/WEB-INF/controller.xml process error. Line: 53. Error message: cvc-complex-type.2.3: Element 'request-map' cannot have character [children], because the type's content type is element-only.
2016-12-07 23:08:48,496 |catalina-startup-1   |UtilXml                       |E| XmlFileLoader: File jndi:/0.0.0.0/imscenter/WEB-INF/controller.xml process error. Line: 60. Error message: cvc-complex-type.2.3: Element 'request-map' cannot have character [children], because the type's content type is element-only.
2016-12-07 23:08:55,539 |OFBiz-JobPoller      |GenericDelegator              |E| Failure in findByCondition operation for entity [JobSandbox]: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool). Rolling back transaction.
org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:774) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:145) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1688) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1723) [ofbiz-entity-test.jar:?]
	at org.ofbiz.service.job.JobManager.reloadCrashedJobs(JobManager.java:294) [ofbiz-service.jar:?]
	at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:223) [ofbiz-service.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 8 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 8 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 8 more
2016-12-07 23:10:20,033 |-0.0.0.0-8443-exec-1 |SequenceUtil                  |E| General error in getting a sequenced ID
java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.SequenceUtil$SequenceBank.fillBank(SequenceUtil.java:195) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.SequenceUtil$SequenceBank.getNextSeqId(SequenceUtil.java:140) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.SequenceUtil$SequenceBank.access$000(SequenceUtil.java:106) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.SequenceUtil.getNextSeqId(SequenceUtil.java:76) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.getNextSeqIdLong(GenericDelegator.java:2395) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.getNextSeqId(GenericDelegator.java:2354) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.getNextSeqId(GenericDelegator.java:2347) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericEntity.setNextSeqId(GenericEntity.java:625) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.createSetNextSeqId(GenericDelegator.java:749) [ofbiz-entity-test.jar:?]
	at org.ofbiz.webapp.stats.VisitHandler.getVisitor(VisitHandler.java:238) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:192) [ofbiz-webapp.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620) [servlet-api-3.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-3.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:317) [ofbiz-webapp.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436) [tomcat-7.0.68-catalina.jar:7.0.68]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078) [tomcat-7.0.68-tomcat-coyote.jar:7.0.68]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) [tomcat-7.0.68-tomcat-coyote.jar:7.0.68]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-7.0.68-tomcat-coyote.jar:7.0.68]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-7.0.68-tomcat-coyote.jar:7.0.68]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	... 41 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	... 41 more
2016-12-07 23:10:20,038 |-0.0.0.0-8443-exec-1 |SequenceUtil                  |E| Fill bank failed, returning null
2016-12-07 23:12:57,077 |OFBiz-config-0       |DatabaseUtil                  |E| Unable to establish a connection with the database for helperName [localposttenant]... Error was: java.sql.SQLException: Unable to acquire a new connection from the pool
2016-12-07 23:12:57,077 |OFBiz-config-2       |DatabaseUtil                  |E| Unable to establish a connection with the database for helperName [localpostolap]... Error was: java.sql.SQLException: Unable to acquire a new connection from the pool
2016-12-07 23:12:57,077 |OFBiz-config-0       |DatabaseUtil                  |E| Unable to establish a connection with the database, no additional information available.
2016-12-07 23:12:57,077 |OFBiz-config-2       |DatabaseUtil                  |E| Unable to establish a connection with the database, no additional information available.
2016-12-07 23:12:57,077 |OFBiz-config-0       |DatabaseUtil                  |E| Could not get table name information from the database, aborting.
2016-12-07 23:12:57,077 |OFBiz-config-2       |DatabaseUtil                  |E| Could not get table name information from the database, aborting.
2016-12-07 23:12:57,078 |OFBiz-config-1       |DatabaseUtil                  |E| Unable to establish a connection with the database for helperName [localpostnew]... Error was: java.sql.SQLException: Unable to acquire a new connection from the pool
2016-12-07 23:12:57,078 |OFBiz-config-1       |DatabaseUtil                  |E| Unable to establish a connection with the database, no additional information available.
2016-12-07 23:12:57,078 |OFBiz-config-1       |DatabaseUtil                  |E| Could not get table name information from the database, aborting.
2016-12-07 23:12:59,304 |main                 |GenericDelegator              |E| Failure in removeByCondition operation for entity [ServiceSemaphore]: org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)). Rolling back transaction.
org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool))
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1202) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1110) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1091) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1084) [ofbiz-entity-test.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:111) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:142) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getInstance(ServiceDispatcher.java:176) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getLocalDispatcher(ServiceDispatcher.java:153) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory.createLocalDispatcher(GenericDispatcherFactory.java:40) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceContainer.getLocalDispatcher(ServiceContainer.java:90) [ofbiz-service.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getLocalDispatcher(EntityServiceFactory.java:34) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getDispatchContext(EntityServiceFactory.java:39) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.eca.DelegatorEcaHandler.setDelegator(DelegatorEcaHandler.java:53) [ofbiz-entityext.jar:?]
	at org.ofbiz.entity.GenericDelegator.initEntityEcaHandler(GenericDelegator.java:333) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.DelegatorFactory.getDelegator(DelegatorFactory.java:42) [ofbiz-entity-test.jar:?]
	at org.ofbiz.catalina.container.CatalinaContainer.init(CatalinaContainer.java:190) [ofbiz-catalina.jar:?]
	at org.ofbiz.base.container.ContainerLoader.loadContainer(ContainerLoader.java:185) [ofbiz-base.jar:?]
	at org.ofbiz.base.container.ContainerLoader.load(ContainerLoader.java:121) [ofbiz-base.jar:?]
	at org.ofbiz.base.start.Start.initStartLoaders(Start.java:273) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.init(Start.java:241) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.main(Start.java:127) [ofbiz.jar:?]
Caused by: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	... 22 more
2016-12-07 23:12:59,336 |main                 |ServiceDispatcher             |E| null
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)) (Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)))
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1156) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1110) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1091) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByAnd(GenericDelegator.java:1084) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:111) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.<init>(ServiceDispatcher.java:142) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getInstance(ServiceDispatcher.java:176) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.getLocalDispatcher(ServiceDispatcher.java:153) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory.createLocalDispatcher(GenericDispatcherFactory.java:40) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceContainer.getLocalDispatcher(ServiceContainer.java:90) [ofbiz-service.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getLocalDispatcher(EntityServiceFactory.java:34) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.EntityServiceFactory.getDispatchContext(EntityServiceFactory.java:39) [ofbiz-entityext.jar:?]
	at org.ofbiz.entityext.eca.DelegatorEcaHandler.setDelegator(DelegatorEcaHandler.java:53) [ofbiz-entityext.jar:?]
	at org.ofbiz.entity.GenericDelegator.initEntityEcaHandler(GenericDelegator.java:333) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.DelegatorFactory.getDelegator(DelegatorFactory.java:42) [ofbiz-entity-test.jar:?]
	at org.ofbiz.catalina.container.CatalinaContainer.init(CatalinaContainer.java:190) [ofbiz-catalina.jar:?]
	at org.ofbiz.base.container.ContainerLoader.loadContainer(ContainerLoader.java:185) [ofbiz-base.jar:?]
	at org.ofbiz.base.container.ContainerLoader.load(ContainerLoader.java:121) [ofbiz-base.jar:?]
	at org.ofbiz.base.start.Start.initStartLoaders(Start.java:273) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.init(Start.java:241) [ofbiz.jar:?]
	at org.ofbiz.base.start.Start.main(Start.java:127) [ofbiz.jar:?]
Caused by: org.ofbiz.entity.GenericDataSourceException: Generic Entity Exception occured in deleteByCondition (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool))
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1202) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:327) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1223) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.deleteByCondition(GenericDAO.java:1199) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.removeByCondition(GenericHelperDAO.java:166) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.removeByCondition(GenericDelegator.java:1140) ~[ofbiz-entity-test.jar:?]
	... 20 more
2016-12-07 23:13:08,518 |catalina-startup-2   |UtilXml                       |E| XmlFileLoader: File jndi:/0.0.0.0/imscenter/WEB-INF/controller.xml process error. Line: 53. Error message: cvc-complex-type.2.3: Element 'request-map' cannot have character [children], because the type's content type is element-only.
2016-12-07 23:13:08,520 |catalina-startup-2   |UtilXml                       |E| XmlFileLoader: File jndi:/0.0.0.0/imscenter/WEB-INF/controller.xml process error. Line: 60. Error message: cvc-complex-type.2.3: Element 'request-map' cannot have character [children], because the type's content type is element-only.
2016-12-07 23:13:15,510 |OFBiz-JobPoller      |GenericDelegator              |E| Failure in findByCondition operation for entity [JobSandbox]: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool). Rolling back transaction.
org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:774) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:145) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1688) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1723) [ofbiz-entity-test.jar:?]
	at org.ofbiz.service.job.JobManager.reloadCrashedJobs(JobManager.java:294) [ofbiz-service.jar:?]
	at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:223) [ofbiz-service.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 8 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 8 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 8 more
