2016-12-07 23:57:45,536 |OFBiz-JobPoller      |TransactionUtil               |I| [TransactionUtil.rollback] transaction rolled back
2016-12-07 23:57:45,536 |OFBiz-JobPoller      |JobManager                    |W| Exception thrown while polling JobSandbox: 
org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:774) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:145) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1688) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.service.job.JobManager.poll(JobManager.java:194) [ofbiz-service.jar:?]
	at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:224) [ofbiz-service.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
2016-12-07 23:58:16,853 |OFBiz-JobPoller      |TransactionUtil               |I| [TransactionUtil.rollback] transaction rolled back
2016-12-07 23:58:16,853 |OFBiz-JobPoller      |JobManager                    |W| Exception thrown while polling JobSandbox: 
org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:774) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:145) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1688) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.service.job.JobManager.poll(JobManager.java:194) [ofbiz-service.jar:?]
	at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:224) [ofbiz-service.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
2016-12-07 23:58:47,867 |OFBiz-JobPoller      |TransactionUtil               |I| [TransactionUtil.rollback] transaction rolled back
2016-12-07 23:58:47,868 |OFBiz-JobPoller      |JobManager                    |W| Exception thrown while polling JobSandbox: 
org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:774) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:145) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1688) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.service.job.JobManager.poll(JobManager.java:194) [ofbiz-service.jar:?]
	at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:224) [ofbiz-service.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
2016-12-07 23:59:18,882 |OFBiz-JobPoller      |TransactionUtil               |I| [TransactionUtil.rollback] transaction rolled back
2016-12-07 23:59:18,882 |OFBiz-JobPoller      |JobManager                    |W| Exception thrown while polling JobSandbox: 
org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:774) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:145) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1688) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.service.job.JobManager.poll(JobManager.java:194) [ofbiz-service.jar:?]
	at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:224) [ofbiz-service.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
2016-12-07 23:59:49,897 |OFBiz-JobPoller      |TransactionUtil               |I| [TransactionUtil.rollback] transaction rolled back
2016-12-07 23:59:49,897 |OFBiz-JobPoller      |JobManager                    |W| Exception thrown while polling JobSandbox: 
org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:253) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:356) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:774) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:145) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1688) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.service.job.JobManager.poll(JobManager.java:194) [ofbiz-service.jar:?]
	at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:224) [ofbiz-service.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:120) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:123) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_91]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_91]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_91]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_91]
	at java.net.Socket.<init>(Socket.java:211) ~[?:1.8.0_91]
	at org.postgresql.core.PGStream.<init>(PGStream.java:62) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.makeConnection(Driver.java:386) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.postgresql.Driver.connect(Driver.java:260) ~[postgresql-8.3-604.jdbc3.jar:?]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.LocalXAConnectionFactory.createConnection(LocalXAConnectionFactory.java:62) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.PoolableManagedConnectionFactory.makeObject(PoolableManagedConnectionFactory.java:103) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1185) ~[commons-pool-1.5.7.jar:1.5.7]
	at org.apache.commons.dbcp.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:117) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedConnection.<init>(ManagedConnection.java:55) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.managed.ManagedDataSource.getConnection(ManagedDataSource.java:77) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:55) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:61) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getManagedConnection(ConnectionFactory.java:121) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
	at org.ofbiz.entity.transaction.TransactionFactory.getConnection(TransactionFactory.java:82) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.ConnectionFactory.getConnection(ConnectionFactory.java:97) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:250) ~[ofbiz-entity-test.jar:?]
	... 7 more
